# Generated by Django 4.0.4 on 2022-07-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='def.jpg', upload_to='media'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
