# Generated by Django 4.0.4 on 2022-07-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cloth_size',
            field=models.CharField(blank=True, choices=[('XS', 'X-Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X-Large')], max_length=2),
        ),
    ]
