# Generated by Django 4.0.4 on 2022-07-31 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cloth_size',
            new_name='size',
        ),
    ]
